// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stsmdgiryuhsqcinjcys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0c21kZ2lyeXVoc3FjaW5qY3lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzU1NTUsImV4cCI6MjA2NDIxMTU1NX0.b5roUbcbid3zR8TJ02tTk-ZwYV3jvgsrH-5ATC75yQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);